[profile.default]
solc_version = "0.8.34"
evm_version = "prague"

optimizer = true
optimizer_runs = 200

remappings = [
  "@solady=lib/solady/",
  "@forge=lib/forge-std/src/"
]

via_ir = true

fs_permissions = [{ access = "read", path = "./SLOW.html"}, { access = "read", path = "./deploy_artifacts"}]

[fmt]
line_length = 100

[rpc_endpoints]
main = "https://ethereum-rpc.publicnode.com"