[profile.default]
solc_version = "0.8.28"
evm_version = "cancun"

optimizer = true
optimizer_runs = 9_999_999

remappings = [
  "@solady=lib/solady/",
  "@soledge=lib/soledge/",
  "@forge=lib/forge-std/src/"
]

via_ir = true

fs_permissions = [{ access = "read", path = "./frontend/index.html"}]

[fmt]
line_length = 100

[rpc_endpoints]
main = "https://ethereum-rpc.publicnode.com"
base = "https://rpc.ankr.com/base"
poly = "https://rpc.ankr.com/polygon"
opti = "https://rpc.ankr.com/optimism"
arbi = "https://rpc.ankr.com/arbitrum"